version: "3.8"
services:
  database:
    build: ./database
    ports:
      - 5432:5432
  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      backend:
        condition: service_healthy