version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
  database:
    build: ./database
    ports:
      - 5432:5432
  backend:
    build: ./backend
    ports:
      - 8000:8000