version: "3.8"
services:
  database:
    build: ./database
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL","pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 100
  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build: ./frontend
    ports:
      - 80:80